// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timers.Persistence;

namespace Timers.Persistence.Migrations
{
    [DbContext(typeof(TimersDbContext))]
    partial class TimersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("Timers.Domain.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("GameSettingId");

                    b.Property<int>("HomeTeamId");

                    b.Property<int>("HomeTeamScore");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("VisitorTeamId");

                    b.Property<int>("VisitorTeamScore");

                    b.HasKey("GameId");

                    b.HasIndex("GameSettingId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Timers.Domain.Entities.GameSetting", b =>
                {
                    b.Property<int>("GameSettingId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCountdown");

                    b.Property<int>("MaxPlayersAllowed");

                    b.Property<int>("MinutesPerPeriod");

                    b.Property<string>("Name");

                    b.Property<int>("Periods");

                    b.HasKey("GameSettingId");

                    b.ToTable("GameSettings");
                });

            modelBuilder.Entity("Timers.Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Jersey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Timers.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Timers.Domain.Entities.Game", b =>
                {
                    b.HasOne("Timers.Domain.Entities.GameSetting", "GameSetting")
                        .WithMany("Games")
                        .HasForeignKey("GameSettingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Timers.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Timers.Domain.Entities.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Timers.Domain.Entities.Player", b =>
                {
                    b.HasOne("Timers.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
